### ISSUE TITLE
Project Key param does not support 2 characters as mentioned in the docs and the UI

### ISSUE THREAD

**Issue by jan-huso** [jfrog/terraform-provider-project#103]
**Describe the bug**
When trying to add a project with two letters ("da" in this case) the provider gives an error that the key must be 3 - 6 lowercase letters. The documentation states it can be 2 - 20 lowercase letters and the UI states it can be 2 - 32 lowercase letters.

*Provider Error:*

│ Error: invalid value for key (key must be 3 - 6 lowercase alphanumeric characters)
│
│   with module.artifactory_projects["da.yml"].project.project,
│   on modules/artifactoryProject/main.tf line 2, in resource "project" "project":
│    2:     key                     = var.delivery
│
╵

*Documentation:*
[key](https://registry.terraform.io/providers/jfrog/project/latest/docs/resources/project#key) (String) The Project Key is added as a prefix to resources created within a Project. This field is mandatory and supports only 2 - 20 lowercase alphanumeric and hyphen characters. Must begin with a letter. For example: us1a-test.

*UI:*
The Project Key is added as a prefix to resources created within a Project
This field is mandatory and supports only
2 - 32 lowercase alphanumeric characters.
Must begin with a letter.
For example: us1a.

**Expected behavior**
The Provider should let me create or import a project with 2 lowercase letters

**Comment by alexhung** [comment]
@jan-huso Thanks for the report. I'll update the documentation to match the validation logic.

**Comment by jan-huso** [comment]
Thank you!
The provider error was related to me using an old version, with the latest there was no problem creating a project with 2 characters
