### ISSUE TITLE
Unable to install provider in OpenTofu

### ISSUE THREAD

**Issue by fabiankle** [jfrog/terraform-provider-project#108]
**Describe the bug**
When trying to install the jfrog/project provider we get the error

```
Initializing modules...
- customers in modules/customer
Initializing provider plugins...
- Reusing previous version of jfrog/project from the dependency lock file
- Reusing previous version of jfrog/artifactory from the dependency lock file
- Installing jfrog/project v1.4.0...
- Installing jfrog/artifactory v10.3.0...
- Installed jfrog/artifactory v10.3.0 (signed, key ID 6B219DCCD7639232)
Providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://opentofu.org/docs/cli/plugins/signing/
╷
│ Error: Failed to install provider
│ 
│ Error while installing jfrog/project v1.4.0: authentication signature from
│ unknown issuer
╵
```

We tested this is 1.4.0 as well as 1.5.1.

We are using opentofu 1.6.2

Example code

```
provider "artifactory" {
}

provider "project" {
}


terraform {
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "10.3.0"
    }
    project = {
      source  = "jfrog/project"
      version = "1.4.0"
    }
  }

  required_version = ">=1.0"
}
```

**Expected behavior**
Being able to install the provider.

I hope this is the right place for this issue! Thank you for your help!

**Comment by alexhung** [comment]
@fabiankle Thanks for the report. OpenTofu registry only allows one key pair for signing providers whereas Terraform allows multiple (probably a legacy issue). Right now we are using 2 different key pairs for signing our providers. We will need to switch to signing all with one key pair so OpenTofu registry is happy.

**Comment by alexhung** [comment]
@fabiankle Signing key is updated in OpenTofu registry: https://github.com/opentofu/registry/pull/331

**Comment by fabiankle** [comment]
Tested this as well now, works - thank you! (Btw now it fails for `artifactory`, but of course this is another repo/provider)
