### ISSUE TITLE
Projects support

### ISSUE THREAD

**Issue by ADSapozhnikov** [jfrog/terraform-provider-project#15]
**Is your feature request related to a problem? Please describe.**
We use jfrog terraform provider. We want to setup [projects ](https://www.jfrog.com/confluence/display/JFROG/Projects) but now its impossible 

**Describe the solution you'd like**
We need to add resource for create Project with provide additional data: Storage Quota, Groups, Repository linking, etc

Any plans to add this functionality?

**Comment by alexhung** [comment]
@ADSapozhnikov This is indeed close to ready to be released. We have a few administrative, CI/CD tasks to complete before we can cut an official release.

**Comment by alexhung** [comment]
@ADSapozhnikov FYI, v1.0.0 is released at https://registry.terraform.io/providers/jfrog/project/latest

**Comment by ADSapozhnikov** [comment]
@alexhung awesome! Thank for your work! We will start working with this feature at the next week)
