### ISSUE TITLE
Breaking change in project resource

### ISSUE THREAD

**Issue by ljupchokotev** [jfrog/terraform-provider-project#154]
**Describe the bug**
The project resource has introduced attributes like `use_project_repository_resource` which is set to `true` by default, meaning existing code will break as the `repos` attribute will be ignored.

This was added in a minor version change. I would expect these new attributes to be set to `false` by default, and changed to `true` only in a major version update.

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue): Nothing to do with a Terraform configuration, just any `project_project` resource which uses `repos`.
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: 7.84.20
- [x] Your version of terraform: 1.6.6

**Expected behavior**

A minor version upgrade of a provider should not introduce breaking changes. The `repos` attribute should still be functional even though it is deprecated.

**Additional context**

**Comment by alexhung** [comment]
@ljupchokotev You're correct that it should have been a major version change when the update was originally released. My apology on that mistake.

The reason behind `use_project_repository_resource` attribute default to being `true` is that the `repos` attribute is not a good solution. The new `project_repository` resource is a huge improvement and thus we were actively trying to discourage any new users from using `repos` attribute.

We feel that the trade off of requiring the addition of `use_project_repository_resource = true` was minor and acceptable to speed up adaption of `project_repository` resource while allowing existing users to continue using `repos` attribute until they migrate.
