### ISSUE TITLE
Add "read only" option to the new "repo shared with" resource to reflect GUI settings

### ISSUE THREAD

**Issue by jan-huso** [jfrog/terraform-provider-project#156]
**Is your feature request related to a problem? Please describe.**
We use the "Share with" feature in Artifactory and want to set it via terraform. With the newly released resource we can share repos between projects but the option to share it as read only is missing.

**Describe the solution you'd like**
Add an option in the resource to share a repo as read only

**Comment by alexhung** [comment]
@jan-huso I've been waiting for a REST API fix to be released for a while. It has been blocking this feature but the fix is in Artifactory v7.94.0 so expect this feature to be released soon.
