### ISSUE TITLE
Support for Mac M1 (darwin_arm64)

### ISSUE THREAD

**Issue by samcarpentier** [jfrog/terraform-provider-project#19]
This provider is currently only available for amd64 processors on Mac (Darwin). Support for new Mac M1 processors will require the code to be compiled for `darwin_arm64`.

### Current behaviour

```
$  terraform init

Initializing the backend...

Initializing provider plugins...
- Finding jfrog/project versions matching "1.0.1"...
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/jfrog/project v1.0.1 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

**Comment by alexhung** [comment]
@samcarpentier Version 1.0.2 is built and uploaded to TF Registry but it isn't showing up there yet. I've contacted TF support so we'll have to wait and see.

**Comment by alexhung** [comment]
@samcarpentier v1.0.2 is up on Terraform Registry
