### ISSUE TITLE
Project key must be 3 - 6 lowercase alphanumeric characters

### ISSUE THREAD

**Issue by martinm82** [jfrog/terraform-provider-project#22]
**Describe the bug**
`terraform validate` says that project keys must be 3-6 characters only. This seems to be fine for Artifactory 7.21.12 (on-premise) but on Artifactory Cloud (7.34.4) one can use 3-10 characters.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: `"version" : "7.34.4",  "revision" : "73404900"`
- [ ] Your version of terraform: 1.1.0

**Expected behavior**
While creating projects against Artifactory Cloud 7.34.4 we get the info that only 3-6 characters are allowed whereas on 7.34.4 3-10 are allowed.

**Additional context**

**Comment by alexhung** [comment]
@martinm82 Thanks for the report. We'll need to apply version specific validations.

**Comment by dasmanas** [comment]
Referred release notes at https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.27.37273. From Artifactory version **7.27.3** as part of **Project-related Enhancements**

Increased the number of characters supported for a Project key up to 10 chars.

**Comment by dasmanas** [comment]
@martinm82 we completed the research and can see that Artifactory's Terraform provider is supporting the Project Key validation as per the latest Artifactory release. Can you please check on which release of Provider you are on?
`terraform version|grep registry.terraform.io/jfrog/artifactory|awk '{ print $4 }'`

For latest version please check https://registry.terraform.io/providers/jfrog/artifactory
