### ISSUE TITLE
Changing project key not supported

### ISSUE THREAD

**Issue by martinm82** [jfrog/terraform-provider-project#23]
**Describe the bug**
Based on the Artifactory REST API it is not possible to change the key of an already existing project. When doing this in Terraform we get an error saying:

```
{
│   "errors" : [ {
│     "code" : "BAD_REQUEST",
│     "message" : "project key mismatch requested project key doesn't match the body project key"
│   } ]
│ }
```

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: 7.34.4 Artifactory Cloud
- [x] Your version of terraform: 1.0.11

**Expected behavior**
Either it should be not allowed to rename a key of a project or it should be implemented by re-creating the project.

**Additional context**

**Comment by alexhung** [comment]
@martinm82 Thanks for the report! We'll add the `ForceNew` field to the `project.key` attribute.
