### ISSUE TITLE
Unable to assign large number of existing repos to project

### ISSUE THREAD

**Issue by alexhung** [jfrog/terraform-provider-project#27]
**Describe the bug**
When assigning a large number (200+) existing repos to project(s) using the `repos` attribute, some assignments fail with 400 error. The error message suggests Artifactory isn't able to service all the concurrent API calls.

**Expected behavior**
All the repos be assigned to the respective projects

**Additional context**

See https://github.com/jfrog/terraform-provider-artifactory/issues/329#issuecomment-1056898960

**Comment by alexhung** [comment]
Workaround applied. The underlying issue remains to be resolved by Artifactory

**Comment by chb0github** [comment]
@alexhung whats status on this ticket?

**Comment by chb0github** [comment]
A best effort workaround exists - this is a limitation of the platform and not this provider
