### ISSUE TITLE
Edge Nodes Failing License Check

### ISSUE THREAD

**Issue by mcaulifn** [jfrog/terraform-provider-project#51]
**Describe the bug**
Edge nodes are failing the license check. `check_license = false` is being required to work around issue.

**Requirements for and issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
Edge nodes should not need to have the license check bypassed as they are included in the necessary license levels.

**Additional context**

```sh
curl -H "Authorization: Bearer $TOKEN"  https://xxxx.jfrog.io/artifactory/api/system/license
{
  "type" : "Edge",
  "validThrough" : "N/R",
  "licensedTo" : "Artifactory Online Dedicated"
}
```

Terraform v1.2.5

provider registry.terraform.io/jfrog/artifactory v6.11.2
provider registry.terraform.io/jfrog/project v1.1.3

**Comment by alexhung** [comment]
@mcaulifn [v1.1.5](https://registry.terraform.io/providers/jfrog/project/1.1.5) is released. Can you re-test?

**Comment by mcaulifn** [comment]
Looks like it works. Thank you!
