### ISSUE TITLE
Fails to create project with Could not find resource `charts.bitnami.com`; type `repo` in Projects configuration

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/terraform-provider-project#55]
https://github.com/jfrog/terraform-provider-project/blob/8462602f6c1239ce25867536052b4d6db8642024/pkg/project/resource_project_repo.go#L162

If we try to create a project and the artifactory already have repositories shared with all projects, it fails to create project with the following error message:

```
╷
│ Error: failed to delete repos for project: failed to delete repo charts.bitnami.com: 
│ 404 DELETE <OMITTED_JFROG_URL>/access/api/v1/projects/_/attach/repositories/<REPO_KEY>
│ {
│   "errors" : [ {
│     "code" : "NOT_FOUND",
│     "message" : "Could not find resource `<REPO_KEY>`; type `repo` in Projects configuration"
│   } ]
│ }
│

```

provider version 1.1.7
jfrog version, enterprise plus latest available.

test case:
create remote repo, share with all projects:
![image](https://user-images.githubusercontent.com/30481051/192373003-34570ee6-8d8c-4415-bb96-ec8c6cbd6c2b.png)

if we create the project via UI, the remote gets created successfully. 

if we create the project using this provider, it fails with the above error message.

what I expect: projects to be created.

---

from my humble understanding of golang, I traced to the following:

first create project
https://github.com/jfrog/terraform-provider-project/blob/8462602f6c1239ce25867536052b4d6db8642024/pkg/project/resource_project.go#L342

calls update repos
https://github.com/jfrog/terraform-provider-project/blob/8462602f6c1239ce25867536052b4d6db8642024/pkg/project/resource_project.go#L374

calls readRepos
https://github.com/jfrog/terraform-provider-project/blob/8462602f6c1239ce25867536052b4d6db8642024/pkg/project/resource_project_repo.go#L81

and fetches the projects:
https://github.com/jfrog/terraform-provider-project/blob/8462602f6c1239ce25867536052b4d6db8642024/pkg/project/resource_project_repo.go#L57

it returns the available shared repos as "to be deleted" and tries to delete

https://github.com/jfrog/terraform-provider-project/blob/8462602f6c1239ce25867536052b4d6db8642024/pkg/project/resource_project_repo.go#L101

then it fails here

https://github.com/jfrog/terraform-provider-project/blob/8462602f6c1239ce25867536052b4d6db8642024/pkg/project/resource_project_repo.go#L156

I could not find a proper GET to see if repo is sharedWithAllProjects, but I found this rest call via UI

https://<JFROG_INSTANCE>/ui/api/v1/ui/admin/repositories/remote/info?projectKey=unassigned

that returns a json list with the following:

![image](https://user-images.githubusercontent.com/30481051/192380334-0cc2affa-0ac3-40b5-b8bd-91fe453ab664.png)

so there is a way to check. Can we check if the repo is already shared in the updateRepos or readRepos method??

**Comment by alexhung** [comment]
@EvertonSA Unfortunately, that API endpoint is private and only should be used for JFrog's UI. The public API doesn't contain that field, yet.

**Comment by EvertonSA** [comment]
@alexhung is there another way to fetch sharedWithAllProducts? there must be a way

**Comment by EvertonSA** [comment]
it must be a way, if there is no way, then we need to request a way

**Comment by EvertonSA** [comment]
@alexhung I have opened a internal jfrog request, ticket number 220316. Can you help me internally to get this somehow solved?

**Comment by EvertonSA** [comment]
I have also tried to add all sharedWithAllProjects repositories to `repos` and it suceeds to create, but it fails to delete with same error

**Comment by EvertonSA** [comment]
i will test with version 1.1.8, because I think if we have the shared remotes already in the project config this might work.

**Comment by EvertonSA** [comment]
@alexhung my assumptions are correct and version 1.1.8 correct this.
