### ISSUE TITLE
Possible logic negation bug on block_deployments_on_limit

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/terraform-provider-project#62]
**Describe the bug**
When managing Projects via this provider, whatever value is set for block_deployments_on_limit, the OPPOSITE of this value is being set on the actual project.

In the API the underlying value is called soft_limit. As there is no documentation around the value of this field we can't be 100% sure what JFrog meant this field to mean, but what is true is that if you make an API call for a Project with Block Deployment Beyond Limit set to TRUE, soft_limit will be FALSE in the resulting API GET. The inverse is also true - if you make an API call for a Project with Block Deployment Beyond Limit set to FALSE, soft_limit will be TRUE in the resulting API GET. Either this is intentional or there is a UI bug, I can't be sure which. 

The Terraform provider code does this (https://github.com/jfrog/terraform-provider-project/blob/master/pkg/project/resource_project.go#L235):

```
SoftLimit:              d.GetBool("block_deployments_on_limit", false),
```

It is setting the value of SoftLimit to be the value of block_deployments_on_limit.

If JFrog intended soft_limit to be the opposite of block_deployments_on_limit then this logic needs to be negated I believe.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform

Terraform v1.3.4
Artifactory version 7.47.10
Provider version 1.1.8

**Expected behavior**
The value set in the Terraform code for block_deployments_on_limit should appear the same in the UI as it the data passed to the provider.

**Additional context**
Speaking with a colleague we could not be sure what soft limit was intended for. It would be really handy if the same wording was used throughout.

**Comment by alexhung** [comment]
@mikeycmccarthy Thanks for the report. We'll investigate.

**Comment by alexhung** [comment]
The `softLimit` field seems no longer has any effect. Previously when this provider was original created, this field determines if the project uses `storageLimitBytes` value.

Now it seems this field is ignored, and the API now uses if `storageLimitBytes` is -1 or not.

I think the best course of action is to deprecate `block_deployments_on_limit` attribute.

**Comment by alexhung** [comment]
Hmmm, I can't reproduce the `soft_limit` having no effect in 7.49.3. I can't find any fixes documented in the release notes either.
