### ISSUE TITLE
Terraform import error for JFrog Project

### ISSUE THREAD

**Issue by RIC-CH-sergio-cruzado** [jfrog/terraform-provider-project#77]
**Describe the bug**

terraform import fail with error: "The configuration for provider["registry.terraform.io/jfrog/project"] depends on values that cannot be determined until apply."

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`:  Artifactory 7.63.5
- [ X] Your version of terraform: 1.4.6
- [X] JFrog project provider version: 1.1.16.

**Expected behavior**

terraform import the project successfully.

**Additional context**

**Comment by danielmkn** [comment]
Hi @RIC-CH-sergio-cruzado! Could you please provide more details, like HCL config, so I can try to reproduce the issue? 
Please, include all the resources you use with the project as well.

**Comment by RIC-CH-sergio-cruzado** [comment]
Hello,
I have updated the jfrog token used (the old one was also a valid token) in the provider config and  the project was finally imported successfully. There must have been a transient error in the provider.
