### ISSUE TITLE
Support sharing repositories between projects

### ISSUE THREAD

**Issue by damacus** [jfrog/terraform-provider-project#80]
## Is your feature request related to a problem? Please describe.

It is currently only possible to share a central repository with new projects via the UI. This is slow and prone to error when there are 100+ projects within the organisation. 

## Describe the solution you'd like

```hcl
resource "artifactory_remote_alpine_repository" "my-remote-alpine" {
  key = "my-remote-alpine"
  url = "http://dl-cdn.alpinelinux.org/alpine"
}

resource "project" "myproject" {
  key          = "myproj"
  display_name = "My Project"
  description  = "My Project"
}

resource "artifactory_share_repository" "my-remote-alpine" {
  repo_name          = artifactory_remote_alpine_repository.my-remote-alpine.name
  target_project_key =  project.myproject.key
}
```

## Additional context

[Share Repository with Target Project API ](https://www.jfrog.com/confluence/display/JFROG/JFrog+Platform+REST+API#JFrogPlatformRESTAPI-ShareRepositorywithTargetProject)

**Comment by shurikg** [comment]
The `target_project_key` needs to be a list. 

It can be a situation in which I want to share the repo for multiple projects.

**Comment by alexhung** [comment]
@damacus @shurikg The upcoming Artifactory v7.90.x will have API support to implement this feature.

**Comment by damacus** [comment]
Thanks!

**Comment by alexhung** [comment]
@shurikg For multiple projects, you can use Terraform `for` expression to create multiple resources.
