### ISSUE TITLE
[FEATURE] Add User/Group to project independent after the project is created

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/terraform-provider-project#83]
**Is your feature request related to a problem? Please describe.**
Right now, when we create users, we create the users before the project and then assign the users we have created to the project. One of my users is looking to automate this at a much higher scale and I cannot offer him that because terraform right now only allows member association during project creation.

**Describe the solution you'd like**
I'm eagerly looking for a `project_user_association`, very similar to how sonarqube does: https://github.com/jdamata/terraform-provider-sonarqube/blob/master/sonarqube/resource_sonarqube_qualitygate_usergroup_association.go

**Describe alternatives you've considered**
I have no other option besides providing dozens of system account references back to the project admin and he has to add one by one.

**Comment by EvertonSA** [comment]
`project_user_association` and `project_group_association` looks like it make more sense.

**Comment by alexhung** [comment]
> terraform right now only allows member association during project creation

@EvertonSA If users are already created **prior** to the project creation, these users can be part of the project configuration, no? I am not seeing the problem from your description.

Also, you can add/remove users from the project **after** it is created by altering the `users` attribute.

**Comment by alexhung** [comment]
@EvertonSA Now I see the use case. Thanks for the explanation.

I haven't tested this yet, but I think if the access token has the project admin permission set correctly (i.e. with ability to manage users for the project) then the 'team01' can still use `project` resource to manage the users/groups attribute for _that_ project.

Of course, as you mentioned, that team uses a separate configuration file/state, so they will need to define the project configuration and import the resource first.

The side effect is that the project states are now in 2 places and synchronization may become an issue. I'm not sure if introducing `project_usergroup_association` resource will solve this issue as this is an inherit trait in your use case.

**Comment by EvertonSA** [comment]
this decision I cannot take because it seems to be a MAJOR change. If jfrog decides that it makes sense, I would be very happy and my internal customer as well. if not, then we will see internally how to proceed. thanks for the insights!
