### ISSUE TITLE
Creation of Project Roles using Terraform

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/terraform-provider-project#85]
I as a Platform engineer would like to provision Project Roles using terraform. 

similar to as implemented here https://github.com/jfrog/terraform-provider-project/issues/78

**Comment by alexhung** [comment]
@EvertonSA Are you currently using the `project.roles` attribute to define your project roles?

**Comment by alexhung** [comment]
@EvertonSA I'm working on this currently and this is what I'm adding:
- new resource `project_role` with same attributes as `project.role` attribute, with extra `project_key` attribute to link it to a project
- new attribute `use_project_role_resource` in `project` resource. This is default to `false` and is used to tell the provider if you are using `project.role` attribute or `project_role` resource to manage your project roles.

So if you are currently using `project.role` attribute. Nothing needs to change.

If you wish to use the new `project_role` resource, set `project.use_project_role_resource` to `true` and add `project_role` resources to your configuration:

```tf
resource "project" "myproj" {
  key = "myprojkey"
  ...
  // no `role` attribute
}

resource "project_role" "myrole" {
  name        = "myrole"
  project_key = "myprojectkey"
  ...
}
```

This should take care of both existing configuration and new comers.

**Comment by EvertonSA** [comment]
👍🏿

**Comment by alexhung** [comment]
@mikeycmccarthy So the process to migrate from using the old attribute `project.roles` to new resource `project_role` should look something like this:

* Assuming you already have a role (`Test Role`) in the `project.roles` attribute
```tf
resource "project" "test-proj" {
  key   = "testproj"
  roles = ["Test Role"]
}
```
* First you define the new role resource (without applying this config)
```tf
resource "project" "test-proj" {
  roles = ["Test Role"]
}

resource "project_role" "test-role" {
  name        = "Test-Role"
  project_key = project.test-proj.key
}
```
* Then import the existing role from Artifactory into this new resource:
```sh
terraform import project_role.test-role testproj:Test-Role
```
* Once the resource is imported successfully, use `use_project_role_resource` attribute to disable role management in `project` resource
```tf
resource "project" "test-proj" {
  key                       = "testproj"
  roles                     = ["Test Role"]
  use_project_role_resource = true
}
```
* After verifying everything is working as intended (e.g. `terraform plan` return no changes), you can safely remove the role from `project.roles`.
