### ISSUE TITLE
Importing project environment shows diff

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/terraform-provider-project#90]
When create environment resource, everything goes well. When importing an existing project environment, some weird behavior happens:

Prerequirement to replicate:
- have a manually created environment named  "platform-dta"

Then follows the process:
add the following to your terraform
```
resource "project_environment" "platform-dta" {
  name        = "platform-dta"
  project_key = "team01"
}
```
Run import command:
terraform import project_environment.platform-dta team01:platform-dta

Run terraform plan:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place


Terraform will perform the following actions:

 

  # project_environment.platform-dta will be updated in-place
  ~ resource "project_environment" "platform-dta" {
        id          = "adat-common-prd"
      ~ name        = "common-prd" -> "platform-dta"
        # (1 unchanged attribute hidden)
    }
 ```
 
 common-prd is an environment that already exists, and it is not intented to be managed by terraform now (it will be in the future).

what my colleague observed is that the import is using the "last" available environment.

**Comment by mikeycmccarthy** [comment]
We're actually seeing the same issue on an earlier version (1.2.1). We're not doing an import, we create one custom project environment, and then after it is created when we create a second custom environment for the project, Terraform tells us it wants to change the first one.

We've confirmed it is the same in the newest version as well (1.3.3)

**Comment by Sarcasm0naut** [comment]
I'm experiencing precisely the same thing @mikeycmccarthy described.

**Comment by alexhung** [comment]
@EvertonSA @mikeycmccarthy @Sarcasm0naut Thanks for the report. I was out on vacation last week, hence the radio silence.

**Comment by mikeycmccarthy** [comment]
Amazing, thank you @alexhung !

**Comment by Sarcasm0naut** [comment]
Thank you @alexhung, highly appreciated.

**Comment by EvertonSA** [comment]
my internal user also confirms it works now
