### ISSUE TITLE
Deleting project fails sometimes

### ISSUE THREAD

**Issue by pho-enix** [jfrog/terraform-provider-project#96]
**Describe the bug**

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
JFrog Platform SaaS
- [x] Your version of terraform
v1.5.7

**How to reproducte**
1. Create terraform config with 1 `project` that links to 3 virtual, 3 remote and 3 local repos using the `repos` key.
2. Apply config. Project is successfully created and has all 9 repos listed
3. Perform terraform destroy
4. In arround 30% of executions there is the error:
```
400 DELETE https://xxxxxx.jfrog.io/access/api/v1/projects/project_name
{
  "errors" : [ {
    "code" : "BAD_REQUEST",
    "message" : "project containing resources can't be removed"
  } ]
}
```
5. Checking in the UI you can see that the unassignment of the repos did not work. One repo still shows the project that should have been deleted.

**Workaround**
Execute destroy again and it will work.

**Additional context**

**Comment by alexhung** [comment]
@pho-enix Thanks for the report! Looks like I may need to add some retry code for deletion. (We have similar issue with repos in the Artifactory provider so this isn't unknown.) I'll add this to our plan.
