### ISSUE TITLE
Allow project members to be missing (due to API limitations on checking user availability)

### ISSUE THREAD

**Issue by Danielku15** [jfrog/terraform-provider-project#98]
**Is your feature request related to a problem? Please describe.**
The general access to our artifactory is controled via SSO while we'd like to manage our project and memberships through terraform. Unfortunately project admins have no access to the user list (only [main admins](https://jfrog.com/help/r/jfrog-rest-apis/get-user-details?tocId=s80tAWGpQA2~An1Ardf9Yw)) which is quite contradictive to the UI behavior where you can search for users (API call: GET /ui/api/v1/access/entities/users?filter=<search term>&limit=50&direction=asc)

We have a code managed list of our developers as we also manage our GitHub Enterprise Organization via terraform and would like to grant the same users access to Artifactory. Now it can happen that users haven't logged in yet and there is no account yet in artifactory. 

**Describe the solution you'd like**

It would be great if we can specify for each [member block](https://registry.terraform.io/providers/jfrog/project/latest/docs/resources/project#nestedblock--member) whether it is OK that a user is missing. 

If this flag is set, an error for a missing/unknown user would be ignored. 

Additionally, if the user later logs in and we re-run the apply, the user should be assigned successfully. So likely some information has to be written into the state or be considered in the refresh step that it is detected that a user is missing. 

**Describe alternatives you've considered**
We could flag users separately whether to be created in artifactory but this solution doesn't scale well. 

**Additional context**
Unfortunately this request is more a workaround than a proper solution to user management. But the limitations are rather on the backend (artifactory / projects) due to missing APIs to check for user existence. If there would be an API whether users exist (input: list of usernames, output: whether they exist) we could dynamically generate the right user list before triggering terraform.

Until then I see it as more realistic that this provider might ignore the API errors on assignment.

**Comment by alexhung** [comment]
@Danielku15 Thanks for the suggestion. I'll add this to our plan.

On the topic of fetching a list of users, have you tried: https://jfrog.com/help/r/jfrog-rest-apis/get-user-list ?

**Comment by Danielku15** [comment]
This is the API i have referenced and referred to in my original post. We are not top level admins of our artifactory but only have a single project in the company shared instance. 

I already started to prepare a change but I have to test first if it works.

**Comment by Danielku15** [comment]
@alexhung I prepared https://github.com/jfrog/terraform-provider-project/pull/99 for our usecase. I opted for a separate resource as it fits our needs a lot better than managing the users as part of the project resource (details in the PR).
